server.port=7070
spring.main.banner-mode=off

# PostgreSQL Database (Neon Cloud)
spring.datasource.url=jdbc:postgresql://ep-fragrant-sound-adlgu4pc-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IkrYh2UTVF0z
spring.datasource.driverClassName=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

server.error.include-message=always
server.error.include-stacktrace=always
